apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic
spec:
  storageClassName: efs-roboshop
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    pupose: efs-dynamic-demo
    project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-dynamic
---
apiVersion: v1
kind: Service
metadata:
  name: efs-dynamic
  labels: 
    pupose: efs-dynamic-demo
    project: roboshop
spec:
  type: LoadBalancer
  selector:
    pupose: efs-dynamic-demo
    project: roboshop
  ports:
  -  protocol: TCP
     port: 80 # service port
     targetPort: 80 # cotainer port
  