apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    project: roboshop
    component: cart
    environment: dev
    tier: backend
  annotations:
    description: "This pod is created to demonstrate pod annotation"
    jenkins: "https://jenkins.com"
spec: 
  containers:
  - name: nginx
    image: nginx