apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
  purpose: replicaset-demo
  project: roboshop
  app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      purpose: replicaset-demo
      project: roboshop
      app: nginx
      
  template:
    metadata:
      labels:
        purpose: replicaset-demo
        project: roboshop
        app: nginx
       
    spec:
      containers:
      - name: nginx
        image: nginx
        
