apiVersion: v1
kind: Service
metadata:
  name: sc-headless-svc
  labels:
    pupose: statefulset
    project: roboshop
spec:
  ports:
  - port: 80
  clusterIP: None
  selector:
    pupose: statefulset
    project: roboshop
---

apiVersion: v1
kind: Service
metadata:
  name: sc-normal-svc
  labels:
    pupose: statefulset
    project: roboshop
spec:
  ports:
  - port: 80
  selector:
    pupose: statefulset
    project: roboshop
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sc-headless
spec:
  selector:
    matchLabels:
      pupose: statefulset
      project: roboshop # has to match .spec.template.metadata.labels
  serviceName: "sc-headless-svc"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        pupose: statefulset
        project: roboshop # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 2Gi